services:
  gas-bot:
    build: .
    container_name: gas_bot
    volumes:
      - ./src:/app/src
      - ./data:/app/data
    environment:
      - DATABASE_URL=sqlite:///data/gas_bot.db
    restart: unless-stopped