services:
  gas-bot:
    build: .
    container_name: gas_bot
    volumes:
      - ./src:/app/src
      - ./data:/app/data
      - ./.env:/app/.env

    environment:
      - DATABASE_URL=${DATABASE_URL}  # берем из .env
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - ADMIN_USER_ID=${ADMIN_USER_ID}
      - ALLOWED_USER_IDS=${ALLOWED_USER_IDS}
    restart: unless-stopped