[project]
name = "bitza-gas-bot"
version = "0.1.0"
description = ""
authors = [
    {name = "sergey",email = "sbitza@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dotenv (>=0.9.9,<0.10.0)",
    "sqlalchemy (>=2.0.44,<3.0.0)",
    "python-telegram-bot (>=22.5,<23.0)",
    "flask (>=3.1.2,<4.0.0)",
    "asyncio (>=4.0.0,<5.0.0)"
]

[tool.poetry.dependencies]
# Python upper bound for locking
python = ">=3.12,<4.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.group.test.dependencies]
pytest = "^8.4.2"
pytest-asyncio = "^1.2.0"
